package org.literacyapp.analytics.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.literacyapp.analytics.model.ApplicationOpenedEvent;
import org.literacyapp.analytics.model.LetterLearningEvent;
import org.literacyapp.analytics.model.NumberLearningEvent;
import org.literacyapp.analytics.model.UsageEvent;

import org.literacyapp.analytics.dao.ApplicationOpenedEventDao;
import org.literacyapp.analytics.dao.LetterLearningEventDao;
import org.literacyapp.analytics.dao.NumberLearningEventDao;
import org.literacyapp.analytics.dao.UsageEventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig applicationOpenedEventDaoConfig;
    private final DaoConfig letterLearningEventDaoConfig;
    private final DaoConfig numberLearningEventDaoConfig;
    private final DaoConfig usageEventDaoConfig;

    private final ApplicationOpenedEventDao applicationOpenedEventDao;
    private final LetterLearningEventDao letterLearningEventDao;
    private final NumberLearningEventDao numberLearningEventDao;
    private final UsageEventDao usageEventDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        applicationOpenedEventDaoConfig = daoConfigMap.get(ApplicationOpenedEventDao.class).clone();
        applicationOpenedEventDaoConfig.initIdentityScope(type);

        letterLearningEventDaoConfig = daoConfigMap.get(LetterLearningEventDao.class).clone();
        letterLearningEventDaoConfig.initIdentityScope(type);

        numberLearningEventDaoConfig = daoConfigMap.get(NumberLearningEventDao.class).clone();
        numberLearningEventDaoConfig.initIdentityScope(type);

        usageEventDaoConfig = daoConfigMap.get(UsageEventDao.class).clone();
        usageEventDaoConfig.initIdentityScope(type);

        applicationOpenedEventDao = new ApplicationOpenedEventDao(applicationOpenedEventDaoConfig, this);
        letterLearningEventDao = new LetterLearningEventDao(letterLearningEventDaoConfig, this);
        numberLearningEventDao = new NumberLearningEventDao(numberLearningEventDaoConfig, this);
        usageEventDao = new UsageEventDao(usageEventDaoConfig, this);

        registerDao(ApplicationOpenedEvent.class, applicationOpenedEventDao);
        registerDao(LetterLearningEvent.class, letterLearningEventDao);
        registerDao(NumberLearningEvent.class, numberLearningEventDao);
        registerDao(UsageEvent.class, usageEventDao);
    }
    
    public void clear() {
        applicationOpenedEventDaoConfig.clearIdentityScope();
        letterLearningEventDaoConfig.clearIdentityScope();
        numberLearningEventDaoConfig.clearIdentityScope();
        usageEventDaoConfig.clearIdentityScope();
    }

    public ApplicationOpenedEventDao getApplicationOpenedEventDao() {
        return applicationOpenedEventDao;
    }

    public LetterLearningEventDao getLetterLearningEventDao() {
        return letterLearningEventDao;
    }

    public NumberLearningEventDao getNumberLearningEventDao() {
        return numberLearningEventDao;
    }

    public UsageEventDao getUsageEventDao() {
        return usageEventDao;
    }

}
