package org.literacyapp.analytics.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import java.util.Calendar;
import org.literacyapp.analytics.dao.converter.CalendarConverter;
import org.literacyapp.analytics.dao.converter.ShapeConverter;
import org.literacyapp.model.enums.content.Shape;

import org.literacyapp.analytics.model.ShapeLearningEvent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SHAPE_LEARNING_EVENT".
*/
public class ShapeLearningEventDao extends AbstractDao<ShapeLearningEvent, Long> {

    public static final String TABLENAME = "SHAPE_LEARNING_EVENT";

    /**
     * Properties of entity ShapeLearningEvent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DeviceId = new Property(1, String.class, "deviceId", false, "DEVICE_ID");
        public final static Property Time = new Property(2, long.class, "time", false, "TIME");
        public final static Property PackageName = new Property(3, String.class, "packageName", false, "PACKAGE_NAME");
        public final static Property StudentId = new Property(4, String.class, "studentId", false, "STUDENT_ID");
        public final static Property Shape = new Property(5, String.class, "shape", false, "SHAPE");
    }

    private final CalendarConverter timeConverter = new CalendarConverter();
    private final ShapeConverter shapeConverter = new ShapeConverter();

    public ShapeLearningEventDao(DaoConfig config) {
        super(config);
    }
    
    public ShapeLearningEventDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SHAPE_LEARNING_EVENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DEVICE_ID\" TEXT NOT NULL ," + // 1: deviceId
                "\"TIME\" INTEGER NOT NULL ," + // 2: time
                "\"PACKAGE_NAME\" TEXT NOT NULL ," + // 3: packageName
                "\"STUDENT_ID\" TEXT," + // 4: studentId
                "\"SHAPE\" TEXT NOT NULL );"); // 5: shape
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SHAPE_LEARNING_EVENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ShapeLearningEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDeviceId());
        stmt.bindLong(3, timeConverter.convertToDatabaseValue(entity.getTime()));
        stmt.bindString(4, entity.getPackageName());
 
        String studentId = entity.getStudentId();
        if (studentId != null) {
            stmt.bindString(5, studentId);
        }
        stmt.bindString(6, shapeConverter.convertToDatabaseValue(entity.getShape()));
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ShapeLearningEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDeviceId());
        stmt.bindLong(3, timeConverter.convertToDatabaseValue(entity.getTime()));
        stmt.bindString(4, entity.getPackageName());
 
        String studentId = entity.getStudentId();
        if (studentId != null) {
            stmt.bindString(5, studentId);
        }
        stmt.bindString(6, shapeConverter.convertToDatabaseValue(entity.getShape()));
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ShapeLearningEvent readEntity(Cursor cursor, int offset) {
        ShapeLearningEvent entity = new ShapeLearningEvent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // deviceId
            timeConverter.convertToEntityProperty(cursor.getLong(offset + 2)), // time
            cursor.getString(offset + 3), // packageName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // studentId
            shapeConverter.convertToEntityProperty(cursor.getString(offset + 5)) // shape
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ShapeLearningEvent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeviceId(cursor.getString(offset + 1));
        entity.setTime(timeConverter.convertToEntityProperty(cursor.getLong(offset + 2)));
        entity.setPackageName(cursor.getString(offset + 3));
        entity.setStudentId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setShape(shapeConverter.convertToEntityProperty(cursor.getString(offset + 5)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ShapeLearningEvent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ShapeLearningEvent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ShapeLearningEvent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
