package ai.elimu.analytics.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ai.elimu.analytics.model.ApplicationOpenedEvent;
import ai.elimu.analytics.model.BootCompletedEvent;
import ai.elimu.analytics.model.LetterLearningEvent;
import ai.elimu.analytics.model.NumberLearningEvent;
import ai.elimu.analytics.model.ShapeLearningEvent;
import ai.elimu.analytics.model.StoryBookLearningEvent;
import ai.elimu.analytics.model.VideoLearningEvent;

import ai.elimu.analytics.dao.ApplicationOpenedEventDao;
import ai.elimu.analytics.dao.BootCompletedEventDao;
import ai.elimu.analytics.dao.LetterLearningEventDao;
import ai.elimu.analytics.dao.NumberLearningEventDao;
import ai.elimu.analytics.dao.ShapeLearningEventDao;
import ai.elimu.analytics.dao.StoryBookLearningEventDao;
import ai.elimu.analytics.dao.VideoLearningEventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig applicationOpenedEventDaoConfig;
    private final DaoConfig bootCompletedEventDaoConfig;
    private final DaoConfig letterLearningEventDaoConfig;
    private final DaoConfig numberLearningEventDaoConfig;
    private final DaoConfig shapeLearningEventDaoConfig;
    private final DaoConfig storyBookLearningEventDaoConfig;
    private final DaoConfig videoLearningEventDaoConfig;

    private final ApplicationOpenedEventDao applicationOpenedEventDao;
    private final BootCompletedEventDao bootCompletedEventDao;
    private final LetterLearningEventDao letterLearningEventDao;
    private final NumberLearningEventDao numberLearningEventDao;
    private final ShapeLearningEventDao shapeLearningEventDao;
    private final StoryBookLearningEventDao storyBookLearningEventDao;
    private final VideoLearningEventDao videoLearningEventDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        applicationOpenedEventDaoConfig = daoConfigMap.get(ApplicationOpenedEventDao.class).clone();
        applicationOpenedEventDaoConfig.initIdentityScope(type);

        bootCompletedEventDaoConfig = daoConfigMap.get(BootCompletedEventDao.class).clone();
        bootCompletedEventDaoConfig.initIdentityScope(type);

        letterLearningEventDaoConfig = daoConfigMap.get(LetterLearningEventDao.class).clone();
        letterLearningEventDaoConfig.initIdentityScope(type);

        numberLearningEventDaoConfig = daoConfigMap.get(NumberLearningEventDao.class).clone();
        numberLearningEventDaoConfig.initIdentityScope(type);

        shapeLearningEventDaoConfig = daoConfigMap.get(ShapeLearningEventDao.class).clone();
        shapeLearningEventDaoConfig.initIdentityScope(type);

        storyBookLearningEventDaoConfig = daoConfigMap.get(StoryBookLearningEventDao.class).clone();
        storyBookLearningEventDaoConfig.initIdentityScope(type);

        videoLearningEventDaoConfig = daoConfigMap.get(VideoLearningEventDao.class).clone();
        videoLearningEventDaoConfig.initIdentityScope(type);

        applicationOpenedEventDao = new ApplicationOpenedEventDao(applicationOpenedEventDaoConfig, this);
        bootCompletedEventDao = new BootCompletedEventDao(bootCompletedEventDaoConfig, this);
        letterLearningEventDao = new LetterLearningEventDao(letterLearningEventDaoConfig, this);
        numberLearningEventDao = new NumberLearningEventDao(numberLearningEventDaoConfig, this);
        shapeLearningEventDao = new ShapeLearningEventDao(shapeLearningEventDaoConfig, this);
        storyBookLearningEventDao = new StoryBookLearningEventDao(storyBookLearningEventDaoConfig, this);
        videoLearningEventDao = new VideoLearningEventDao(videoLearningEventDaoConfig, this);

        registerDao(ApplicationOpenedEvent.class, applicationOpenedEventDao);
        registerDao(BootCompletedEvent.class, bootCompletedEventDao);
        registerDao(LetterLearningEvent.class, letterLearningEventDao);
        registerDao(NumberLearningEvent.class, numberLearningEventDao);
        registerDao(ShapeLearningEvent.class, shapeLearningEventDao);
        registerDao(StoryBookLearningEvent.class, storyBookLearningEventDao);
        registerDao(VideoLearningEvent.class, videoLearningEventDao);
    }
    
    public void clear() {
        applicationOpenedEventDaoConfig.clearIdentityScope();
        bootCompletedEventDaoConfig.clearIdentityScope();
        letterLearningEventDaoConfig.clearIdentityScope();
        numberLearningEventDaoConfig.clearIdentityScope();
        shapeLearningEventDaoConfig.clearIdentityScope();
        storyBookLearningEventDaoConfig.clearIdentityScope();
        videoLearningEventDaoConfig.clearIdentityScope();
    }

    public ApplicationOpenedEventDao getApplicationOpenedEventDao() {
        return applicationOpenedEventDao;
    }

    public BootCompletedEventDao getBootCompletedEventDao() {
        return bootCompletedEventDao;
    }

    public LetterLearningEventDao getLetterLearningEventDao() {
        return letterLearningEventDao;
    }

    public NumberLearningEventDao getNumberLearningEventDao() {
        return numberLearningEventDao;
    }

    public ShapeLearningEventDao getShapeLearningEventDao() {
        return shapeLearningEventDao;
    }

    public StoryBookLearningEventDao getStoryBookLearningEventDao() {
        return storyBookLearningEventDao;
    }

    public VideoLearningEventDao getVideoLearningEventDao() {
        return videoLearningEventDao;
    }

}
